apiVersion: v1
kind: Service # yine service oluşturduk yani trafik yönlendirmesi yapmasını isteyeceğiz.
metadata:
# kubernetes içinde isim çözümleme sistemi var burdaki ismi çözümleyecek. Database.php içindeki sunucu adresi satırına localhost yerine bu ismi yazıcaz.
  name: eczane-db-service
spec:
  type: ClusterIP # dışarıdan erişim kapalı sadece cluster içinden izole erişim var.
  selector: # yine bu etiketteki podları ben yöneticem diye etiket seçtik.
    app: eczane-mysql
  ports:
    - port: 3306

---

apiVersion: apps/v1 # yine kullanılacak api kütüphanesini belirttik
kind: StatefulSet
metadata: # isim verdik buna ulaşabilmek için.
  name: eczane-db-stateful
spec:
  serviceName: "eczane-db-service" # yukarda oluşturduğumuz servis ile bağlı olduğunu belirtiyoruz.
  replicas: 1 # çakışma olmaması için tek replika yaptık.
  selector: # kendi oluşturduğumuz podun alnına etiket yapıştırıyoruz ki yukarıdaki servis onu bulabilsin.
    matchLabels:
	    app: eczane-mysql # ismi verdiğimiz yer ki servis bu isimle bulabilsin.
  template:
    metadata:
	    labels:
	      app: eczane-mysql
	  spec:
	    containers:
	    - name: mysql-konteyner
	      image: mysql:8.0 # docker hubtan resmi mysql imajını çekiyoruz.
		  env:
		  - name: MYSQL_ROOT_PASSWORD
		    valueFrom:
		      secretKeyRef:
			    name: eczane-db-gizli-bilgiler
			    key: sifre
		  - name: MYSQL_DATABASE
		    valueFrom:
		      secretKeyRef:
			    name: eczane-db-gizli-bilgiler
			    key: veritabani_adi
		  ports:
		  - containerPort: 3306
		  volumeMounts: # diskin konteyner içindeki karşılığı.
		  - name: db-kalici-disk
		    mountPath: /var/lib/mysql # Linux  fabrika ayarı olarak verileri buraya kaydeder. k8s'e diyoruz ki burayı izole et ve takacağımız diski
		    # buraya bağla.
  
  volumeClaimTemplates: # kalıcı disk şablonu
  - metadata:
      name: db-kalici-disk
	spec:
	  accessModes: [ "ReadWriteOnce" ] # bu fiziksel diske aynı anda sadece 1 tane node okuyup yazabilsin, tutarlılık için gereklidir.
	  resources: # sistemin derinliklerinde 2Gi fiziksel bir harddisk alanı ayır, bunu mysql poduma bağla.
	    requests:
		  storage: 2Gi