apiVersion: v1
kind: Service # Trafik yonlendirmesi yapmasi icin servis olusturuyoruz.
metadata:
  # Kubernetes icindeki DNS bu ismi cozumleyecek. 
  # Projedeki veritabanı baglanti satirina (connection string) localhost yerine bu ismi yaziyoruz.
  name: eczane-db-service
spec:
  type: ClusterIP # Disaridan erisim kapali, sadece cluster icinden izole erisim var.
  selector:
    app: eczane-mysql # Bu etikete sahip podu yonlendir diyoruz.
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: StatefulSet # Veritabani gibi veri tutarliligi gerektiren yapilar icin StatefulSet kullaniyoruz.
metadata:
  name: eczane-db-stateful # Objeye ulasabilmek icin verdigimiz isim.
spec:
  serviceName: "eczane-db-service" # Yukarida olusturdugumuz servis ile bagliyoruz.
  replicas: 1 # Veri cakislamari olmamasi icin tek replika (tek kopya) olarak calisacak.
  selector:
    matchLabels:
      app: eczane-mysql
  template:
    metadata:
      labels:
        app: eczane-mysql
    spec:
      containers:
        - name: mysql-konteyner
          image: mysql:8.0 # Docker Hub uzerindeki resmi MySQL imajini cekiyoruz.
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eczane-db-gizli-bilgiler
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: eczane-db-gizli-bilgiler
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
          volumeMounts: # Diskin konteyner icindeki karsiligidir.
            - name: db-kalici-disk
              mountPath: /var/lib/mysql # MySQL verileri varsayilan olarak buraya kaydeder, burayi diske bagliyoruz.

  volumeClaimTemplates: # Kalici disk sablonu (Persistent Volume Claim)
    - metadata:
        name: db-kalici-disk
      spec:
        accessModes: [ "ReadWriteOnce" ] # Bu fiziksel diske ayni anda sadece 1 tane node okuyup yazabilsin.
        resources:
          requests:
            storage: 2Gi # Sistemden 2 Gigabyte'lik fiziksel bir depolama alani talep ediyoruz.